# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir nombre del pa\xeds.', max_length=255, unique=True)),
                ('codigo_postal', models.IntegerField(verbose_name='C\xf3digo postal')),
                ('descripcion', models.TextField(blank=True, help_text='Escribir descripci\xf3n del pa\xeds. (Opcional)')),
                ('imagen', models.ImageField(blank=True, help_text='Subir imagen del pa\xeds. (Opcional)', upload_to='imagenes_paises')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Paises',
                'verbose_name': 'Pa\xeds',
                'verbose_name_plural': 'Paises',
            },
        ),
    ]
