# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir nombre del pa\xeds.', max_length=255, unique=True)),
                ('codigo_postal', models.IntegerField(blank=True)),
                ('imagen', models.ImageField(blank=True, help_text='Subir imagen del pa\xeds. (Opcional)', upload_to='imagenes_paises')),
                ('descripcion', models.TextField(blank=True, help_text='Escribir descripci\xf3n del pais. (Opcional)')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Paises',
            },
        ),
    ]
