# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir nombre del \xe1rea.', max_length=255, unique=True)),
                ('siglas', models.CharField(help_text='Escribir siglas del \xe1rea.', max_length=20)),
                ('mision', models.TextField(blank=True, help_text='Escribir misi\xf3n del \xe1rea (Opcional).', null=True)),
                ('vision', models.TextField(blank=True, help_text='Escribir vision del \xe1rea (Opcional).', null=True)),
                ('sector', models.CharField(blank=True, help_text='Escribir nombre del sector del \xe1rea (Opcional).', max_length=255, null=True)),
                ('local', models.CharField(blank=True, help_text='Escribir nombre del local del \xe1rea (Opcional).', max_length=255, null=True)),
                ('zona', models.CharField(blank=True, max_length=20, null=True)),
                ('seccion', models.CharField(blank=True, max_length=20, null=True)),
                ('pabellon', models.CharField(blank=True, max_length=20, null=True)),
                ('edificio', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('piso', models.CharField(blank=True, max_length=20, null=True)),
                ('interior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('referencia', models.CharField(blank=True, help_text='Escribir referencia (Opcional).', max_length=255, null=True)),
                ('logotipo', models.ImageField(blank=True, help_text='Subir logotipo del \xe1rea (Opcional).', upload_to='logotipo_area')),
                ('anexo_telefonico', models.PositiveIntegerField(blank=True, default=0, help_text='Escribir n\xfamero de anexo telefonico del \xe1rea (Opcional).')),
                ('fax_interno', models.PositiveIntegerField(blank=True, default=0, help_text='Escribir n\xfamero de fax (Interno) del \xe1rea (Opcional).')),
                ('email_institucional', models.EmailField(blank=True, help_text='Escribir E-Mail (Opcional).', max_length=255, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Escribir descripci\xf3n del \xe1rea (Opcional).', null=True)),
                ('observacion', models.TextField(blank=True, help_text='Escribir observaci\xf3n del \xe1rea (Opcional).', null=True)),
                ('fecha_creacion', models.DateField(blank=True, default='01/01/1980', null=True)),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Areas',
                'verbose_name': '\xc1rea',
                'verbose_name_plural': '\xc1reas',
            },
        ),
    ]
