# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglas', models.CharField(help_text='Escribir siglas de la entidad.', max_length=25)),
                ('anio', models.DateTimeField(default=datetime.datetime(2016, 3, 2, 21, 17, 26, 629000))),
                ('numero_documento', models.PositiveIntegerField()),
                ('origen', models.BooleanField(default=1)),
                ('asunto', models.CharField(help_text='Escribir asunto del documento o Expediente (Opcional).', max_length=225)),
                ('numero_folio', models.PositiveIntegerField()),
                ('fecha_recepcion', models.DateTimeField(default=datetime.datetime(2016, 3, 2, 21, 17, 26, 629000))),
                ('fecha_vencimiento_procedimiento', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Escribir descripci\xf3n del documento o Expediente (Opcional).', null=True)),
                ('observacion', models.TextField(blank=True, help_text='Escribir observaci\xf3n del documento o Expediente (Opcional).', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Documentos',
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
