# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prioridades', '0001_initial'),
        ('documentos', '0003_documento_nexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prioridades.Prioridad'),
        ),
    ]
