# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('situaciones', '0001_initial'),
        ('documentos', '0004_documento_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='situacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situaciones.Situacion'),
        ),
    ]
