# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
        ('distritos', '0002_distrito_provincia'),
        ('empleados', '0006_empleado_profesion'),
        ('entidades', '0002_entidad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir sede.', max_length=255, unique=True)),
                ('nombre_direccion', models.CharField(help_text='Escribir nombre de la direcci\xf3n de la sede.', max_length=255)),
                ('local', models.CharField(blank=True, help_text='Escribir nombre del local de la sede. (Opcional).', max_length=255, null=True)),
                ('pabellon', models.CharField(blank=True, max_length=20, null=True)),
                ('edificio', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('piso', models.CharField(blank=True, max_length=20, null=True)),
                ('interior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cuadra', models.CharField(blank=True, max_length=20, null=True)),
                ('manzana', models.CharField(blank=True, max_length=20, null=True)),
                ('lote', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_lote', models.CharField(blank=True, max_length=20, null=True)),
                ('denominacion', models.CharField(blank=True, help_text='Escribir denominaci\xf3n (Opcional).', max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, help_text='Escribir referencia (Opcional).', max_length=255, null=True)),
                ('observacion_direccion', models.CharField(blank=True, help_text='Escribir observaci\xf3n de la direcci\xf3n (Opcional).', max_length=255, null=True)),
                ('pagina_web', models.URLField(help_text='Escribir nombre de la p\xe1gina web de la sede (Opcional).', max_length=255, unique=True)),
                ('telefono', models.PositiveIntegerField(blank=True, default=0, help_text='Escribir n\xfamero de tel\xe9fono de la sede (Opcional).')),
                ('fax', models.PositiveIntegerField(blank=True, default=0, help_text='Escribir n\xfamero de fax de la sede (Opcional).')),
                ('email', models.EmailField(help_text='Escribir E-Mail de la sede (Opcional).', max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Escribir descripci\xf3n de la \xe1rea (Opcional).', null=True)),
                ('observacion_sede', models.TextField(blank=True, help_text='Escribir observaci\xf3n de la \xe1rea (Opcional).', null=True)),
                ('fecha_creacion', models.DateField(blank=True, default='01/01/1980', null=True)),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distritos.Distrito')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.Entidad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.Estado')),
                ('persona_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Sedes',
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
    ]
