# -*- encoding: utf-8 -*-
"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5copt@^us)m2tk0g7mpds3i44u0n2u&i^v@x37r@)x$dvkp_20'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'paises.apps.PaisesConfig',
    'departamentos.apps.DepartamentosConfig',
    'provincias.apps.ProvinciasConfig',
    'distritos.apps.DistritosConfig',
    'vias.apps.ViasConfig',
    'zonas.apps.ZonasConfig',

    'documentos_identificaciones.apps.DocumentosIdentificacionesConfig',
    'codigos_barras.apps.CodigosBarrasConfig',
    'estados_civiles.apps.EstadosCivilesConfig',
    'grupos_sanguineos.apps.GruposSanguineosConfig',
    'grados_instrucciones.apps.GradosInstruccionesConfig',
    'areas.apps.AreasConfig',
    'cargos.apps.CargosConfig',
    'ocupaciones.apps.OcupacionesConfig',
    'profesiones.apps.ProfesionesConfig',
    'entidades.apps.EntidadesConfig',
    'sedes.apps.SedesConfig',
    'tipos_areas.apps.TiposAreasConfig',
    'tipos_entidades.apps.TiposEntidadesConfig',
    'tipos_empleados.apps.TiposEmpleadosConfig',
    'tipos_documentos.apps.TiposDocumentosConfig',
    'personas.apps.PersonasConfig',
    'empleados.apps.EmpleadosConfig',
    'usuarios.apps.UsuariosConfig',

    'nexos.apps.NexosConfig',

    'documentos.apps.DocumentosConfig',

    'estados.apps.EstadosConfig',
    'prioridades.apps.PrioridadesConfig',
    'situaciones.apps.SituacionesConfig',
    'mensajes.apps.MensajesConfig',
    'bandejas.apps.BandejasConfig',
    'bandejas_mensajes.apps.BandejasMensajesConfig',
    'rest_framework',
    'index.apps.IndexConfig',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #Esribir dirección por defecto de templates.
        'DIRS': [os.path.join(os.path.dirname(__file__) , 'templates').replace('\\','/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': "sql_server.pyodbc",
       'HOST': "127.0.0.1",
       'PORT': '1433',
       'USER': "sa",
       'PASSWORD': "S1st3mas",
       'NAME': "Tramite_Documentario",
       'OPTIONS': {
            'host_is_server': True,
        },
   }
}



# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/
#Configuración de archivos estaticos 
STATIC_URL = '/static/'
#MEDIA -> STATIC
STATIC_ROOT = os.sep.join(os.path.abspath(__file__).split(os.sep)[:-2] + ['static'])

STATICFILES_FINDERS = {
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
}

#Activar cache para archivos estaticos
#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFileStorage'

#Imagenes, audios y videos
MEDIA_ROOT = os.sep.join(os.path.abspath(__file__).split(os.sep)[:-2] + ['media'])
MEDIA_URL  = '/media/'

#Configuración de Usuario 
AUTH_USER_MODEL = 'usuarios.Usuario'

#Configuración de Logueo 
LOGIN_REDIRECT_URL = '/admin/' # LogIn
LOGOUT_REDIRECT_URL = '/'

#LOGIN_URL='/usuario/login'

