# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.PositiveIntegerField(blank=True, help_text='Escribir el n\xfamero de tarjeta. (Opcional)')),
                ('numero_acceso_biometrico', models.PositiveIntegerField(blank=True, help_text='Escribir el n\xfamero de acceso al biom\xe9trico (Opcional)')),
                ('fecha_inicio_contratacion', models.DateField(help_text='Seleccionar fecha de inicio de contrataci\xf3n del empleado.')),
                ('fecha_fin_contratacion', models.DateField(blank=True, help_text='Seleccionar fecha de final de contrataci\xf3n del empleado.', null=True)),
                ('fecha_cese', models.DateTimeField(blank=True, help_text='Seleccionar fecha de cese del empleado.', null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Escribir descripci\xf3n del empleado (Opcional).', null=True)),
                ('observacion', models.TextField(blank=True, help_text='Escribir observaci\xf3n del empleado (Opcional).', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Cargo')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Empleados',
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
