# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesiones', '0001_initial'),
        ('empleados', '0005_empleado_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='profesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesiones.Profesion'),
        ),
    ]
