# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos_identificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir nombre de la entidad.', max_length=255, unique=True)),
                ('siglas', models.CharField(help_text='Escribir siglas de la entidad.', max_length=25)),
                ('numero_documento_identificacion', models.PositiveIntegerField(help_text='Escribir n\xfamero documento identificaci\xf3n.', unique=True)),
                ('email_oficial', models.EmailField(help_text='Escribir E-Mail de la entidad (Opcional).', max_length=255, unique=True)),
                ('pagina_web_oficial', models.URLField(help_text='Escribir nombre de la p\xe1gina web de la entidad (Opcional).', max_length=255, unique=True)),
                ('mision', models.TextField(help_text='Escribir misi\xf3n de la entidad (Opcional).')),
                ('vision', models.TextField(help_text='Escribir vision de la entidad (Opcional).')),
                ('logotipo', models.ImageField(blank=True, help_text='Subir logotipo de la entidad (Opcional).', null=True, upload_to='logotipo_entidad')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Escribir descripci\xf3n de la entidad (Opcional).', null=True)),
                ('observacion', models.TextField(blank=True, help_text='Escribir observaci\xf3n de la entidad (Opcional).', null=True)),
                ('fecha_creacion', models.DateField(blank=True, default='01/01/1980', null=True)),
                ('fecha_cese', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('documento_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos_identificaciones.DocumentoIdentificacion')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Entidades',
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
