# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandejas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandejaMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(default=datetime.datetime(2016, 3, 2, 21, 17, 26, 653000), null=True)),
                ('fecha_envio', models.DateTimeField(default=datetime.datetime(2016, 3, 2, 21, 17, 26, 653000), null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('visto', models.PositiveSmallIntegerField(default=0)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_host', models.CharField(max_length=255)),
                ('direccion_ip', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('bandeja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandejas.Bandeja')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Bandejas_Mensajes',
                'verbose_name': 'Bandeja Mensaje',
                'verbose_name_plural': 'Bandejas Mensajes',
            },
        ),
    ]
