# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensajes', '0001_initial'),
        ('bandejas_mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandejamensaje',
            name='mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Mensaje'),
        ),
    ]
