# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandejas_mensajes', '0003_auto_20160302_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandejamensaje',
            name='fecha_envio',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 2, 21, 25, 16, 347000), null=True),
        ),
        migrations.AlterField(
            model_name='bandejamensaje',
            name='fecha_recepcion',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 2, 21, 25, 16, 347000), null=True),
        ),
    ]
