# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribir nombre del departamento.', max_length=255, unique=True)),
                ('codigo_postal', models.IntegerField(help_text='Escribir c\xf3digo postal del departamento.', verbose_name='C\xf3digo postal')),
                ('descripcion', models.TextField(blank=True, help_text='Escribir descripci\xf3n del departamento. (Opcional)')),
                ('imagen', models.ImageField(blank=True, help_text='Subir imagen del departamento. (Opcional)', upload_to='imagenes_departamentos')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paises.Pais')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'Departamentos',
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
