# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vias', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ultimo_usuario_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_usuario_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persona',
            name='via',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vias.Via'),
        ),
        migrations.AddField(
            model_name='persona',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas.Zona'),
        ),
    ]
